### PR TITLE
Remove KieName and KieIndex from KieApp

### PR DESCRIPTION
**Pull request by bmozaffa**
Simplify logic and remove implementation details of server naming from exposed object yamls
Avoid "-index" when only one deployment is configured, as is often the case
Move the index before postgresql and other artifact types

### CODE REVIEW

**Comment by tchughesiv** [comment]
Have you tested what happens if you increase an already deployed serverSet’s deployments amount from the default of 1 to a greater number?? Do you wind up with the proper amount of server deployments for that serverSet?

**Comment by bmozaffa** [comment]
I haven't, and I was thinking about that at some point. That's just about the naming convention and dropping the "-0" for single deployment, right? When if it's an issue, which it probably is, I think it can be fixed with a different big report and PR through reconciliation logic. I don't know what reconciliation does right now, but would be clean if it could call a function to get what should exist, and another to see what does exist, then delete, update or add to make things right.

Thoughts?

Alternatively another easier fix is to always make the first index blank. But then maybe the second one should be "-2" instead of "-1" to about confusion?

**Comment by bmozaffa** [comment]
I realized at PR time that I had not pulled your updates (rebase), so I had to do that again, late at night, and seems like I screwed it up. I did minimal testing after that, thinking it's a simple rebase, but did a poor job of rebasing... stay tuned!

**Comment by bmozaffa** [comment]
You were right after changing deployments from 1 to 2... reproduced and fixed, in different PR, that would just be one commit on top of this one. This could be merged first, and then I can rebase the other if needed, though if you merge without a commit message (drop-down), that shouldn't be necessary.

**Comment by tchughesiv** [comment]
@bmozaffa let's close this PR and use https://github.com/tchughesiv/kie-cloud-operator/pull/2 instead...

**Pull request closed without merging**
